---

- name: release specific variables
  include_vars: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "../vars"
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: confluence

- name: release specific tasks
  include_tasks: "{{ loop_var }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: "."
      skip: "yes"
  loop_control:
    loop_var: "loop_var"
  tags: confluence

- name: prep file perms
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ confluence_catalina }}", owner: "{{ confluence_owner }}", group: "{{ confluence_group }}", mode: "0755", state: "directory" }
    - { dest: "{{ confluence_home }}", owner: "{{ confluence_owner }}", group: "{{ confluence_group }}", mode: "0755", state: "directory" }
  tags: confluence

- name: unarchive package
  shell: |
    ARCHIVE="`mktemp --suffix=tar.gz`"
    curl -sL {{ confluence_url }} > $ARCHIVE
    tar zxf $ARCHIVE -C {{ confluence_catalina }} --strip-components=1
    chown -Rf {{ confluence_owner }}:{{ confluence_group }} {{ confluence_catalina }}
    rm -rf $ARCHIVE
  args:
    creates: "{{ confluence_catalina }}/bin/start-confluence.sh"
  tags: confluence

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/confluence.j2", dest: "/etc/init.d/confluence", owner: "root", group: "root", mode: "0755" }
    - { src: "opt/atlassian/confluence/bin/setenv.sh.j2", dest: "{{ confluence_catalina }}/bin/setenv.sh", owner: "{{ confluence_owner }}", group: "{{ confluence_group }}", mode: "0644" }
    - { src: "opt/atlassian/confluence/conf/server.xml.j2", dest: "{{ confluence_catalina }}/conf/server.xml", owner: "{{ confluence_owner }}", group: "{{ confluence_group }}", mode: "0644" }
  tags: confluence

- name: enable service
  service:
    name: "confluence"
    enabled: "yes"
  tags: confluence
